# Variáveis instrumentais {#vi}

```{r echo=FALSE}
#para colorir frases
colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color, 
      x)
  } else x
}
```


Em estatística, econometria, epidemiologia e áreas relacionadas, o método de variáveis instrumentais é usado para estimar relações causais, quando experimentos controlados não são viáveis. O método de `r colorize(" variáveis instrumentais ", "blue")`  (_VI_) permite estimações consistentes quando as variáveis explicativas são endógenas.



## Conceito da exogeneidade dos regressores

Nos modelos econométricos estruturais de uma equação a variável dependente `r colorize(" (endógena) ", "blue")` é explicada através de um conjunto de variáveis explicativas (não estocásticas) e do termo de erro. Nos modelos econométricos estruturais de uma equação, as variáveis explicativas são a causa que explicam a variação da variável dependente e a variável endógena reflete o efeito provocado pela variação das variáveis explicativas.
Uma das hipóteses básicas iniciais da regressão MQO admite a ausência de correlação das variáveis explicativas $X_1,\cdots,X_k$ com o termo de erro, isto é $\mbox{Cov}(X_i,\varepsilon)=0$, para todo $i=1,\cdots,k$. Desta forma as variáveis explicativas são consideradas exógenas no modelo tradicional de regressão. Contudo, a hipótese da exogeneidade das variáveis explicativas é muitas vezes infringida. Entre as  causas mais comuns da endogeneidade das variáveis explicativas podemos citar _erros de mensuração das variáveis_, _variável omitida_ e _simultaneidade_.

Quando temos um problema de endogeneidade causado por uma _variável não-observável_,  uma possível solução é a utilização de uma variável `r colorize(" proxy ", "blue")` .



### Variável proxy


No exemplo apresentado por [@wooldridge2016] é considerada a regressão para explicar a **renda** em função do **nível de escolaridade** ($educ$) e a aptidão para determinada tarefa ($aptid$),

 \begin{equation}
  \log(salario)=\beta_0+\beta_1 educ+\beta_2 aptid+u.
  (\#eq:logsal)
 \end{equation}
Observe que $aptid$  é uma variável  inata,  não observável. Podemos esperar que $aptid$ seja correlacionada com $educ$ e, nesse caso, a omissão da variável $aptid$ da  regressão \@ref(eq:logsal) (por motivos que veremos logo mais) torna a estimativa via MQO de $\beta_1$ viciada  e inconsistente. Uma maneira de contornar este problema é substituir a variável $aptid$ por uma variável observável altamente correlacionada com $aptid$ que será usada como proxy para aptidão. Tal variável é denominada variável \emph{proxy} e idealmente deve satisfazer as seguintes condições:

|    a) Ser altamente correlacionada  com a  variável não observada que pretende substituir;

|    b) Não ser correlacionada com o termo de erro da regressão.

Com uma boa proxy, podemos estimar o modelo por MQO e obter ``boas'' estimativas para $\beta_1$ \@ref(eq:logsal). No que segue assumiremos que variáveis proxys não estão à disposição.




### Variável omitida
O modelo \@ref(eq:logsal) pode ser reescrito como
\begin{equation}
 Y=\beta_0+\beta_1X_1+\beta_2X_2+\varepsilon,
 (\#eq:yicorreto)
\end{equation}
$Y$ representa o logaritmo do salário, $X_{1}$ representa a variável educação, $X_2$ a aptidão e $\varepsilon$ representa o termo de erro do modelo, com $\mbox{Cov}(X_i,\varepsilon)=0$, i=1,2. Como já discutimos, a variável aptidão, não é observável e vamos assumir que uma variável proxy para aptidão não está disponível. Omitindo a variável $X_2$ no modelo obtemos
\begin{equation}
Y=\beta_0+\beta_1X_1+\xi
(\#eq:varomitida)
\end{equation}
onde $\xi=\beta_2X_2+\varepsilon$ representa o erro na regressão acima. Estimando ${\beta}=(\beta_0,\beta_1)$ por MQO obtemos
\begin{align*}
\mathbb{E}(\hat{\beta})&=\mathbb{E}\left(\frac{\mbox{Cov}(X_1,Y)}{\mbox{Var}(X_1)}\right)=\mathbb{E}\left(\frac{\mbox{Cov}(X_1,\beta_0+\beta_1X_1+\xi)}{\mbox{Var}(X_1)}\right)\\
&=\mathbb{E}\left(\frac{\beta_1\mbox{Var}(X_1)+\mbox{Cov}(X_1,\xi)}{\mbox{Var}(X_1)}\right)=\mathbb{E}\left(\frac{\beta_1\mbox{Var}(X_1)+\mbox{Cov}(X_1,\xi)}{\mbox{Var}(X_1)}\right)\\
&=\beta_1+\mathbb{E}\left(\frac{\mbox{Cov}(X_1,\xi)}{\mbox{Var}(X_1)}\right),
\end{align*}
de onde segue que o estimador de MQO é não viciado se, e somente se, $\mbox{Cov}(X_1,\xi)=0$. Pode-se mostrar ainda que se $\mbox{Cov}(X_1,\xi)\neq0$, o estimador de MQO será inconsistente. Agora observe que
\[\mbox{Cov}(X_1,\xi)=\mbox{Cov}(X_1,\beta_2X_2+\varepsilon)=\beta_2\mbox{Cov}(X_1,X_2)+\mbox{Cov}(X_1,\varepsilon)=\beta_2\mbox{Cov}(X_1,X_2)\]
que é zero se, e somente se, $\mbox{Cov}(X_1,X_2)=0$, o que nem sempre acontece na prática. Em outras palavras, olhando \@ref(eq:yicorreto) como um modelo geral de onde foi omitida a variável $X_2$ resultando no modelo \@ref(eq:varomitida), se $X_1$ e $X_2$ são correlacionados então o estimador de MQO é viciado e inconsistente!


<br>


```{example tabaco}
Suponha que um pesquisador deseja estimar o efeito causal do tabagismo sobre a saúde geral, como em @leigh2004 ). Em princípio, a existência de correlação entre a saúde e o hábito de fumar não implica necessariamente que o fumo piora a saúde, porque outras variáveis podem afetar tanto a saúde quanto o hábito de fumar. Por exemplo, pode ocorrer por acaso que pessoas de uma certa cidade exposta à poluição radioativa fumem muito, mas é a poluição que realmente causa problemas de saúde à esta população em estudo. Mesmo que o tabagismo cause realmente problemas, a saúde em si pode afetar o hábito de fumar (digamos, um paciente muito doente pode se sentir instigado a fumar mais). Fazer estudos controlados (por exemplo, colocar uma pessoa num laboratório, sem exposição à poluição, fumando quantidades controladas) pode ser difícil, caro ou anti-ético. Uma opção alternativa, portanto, seria o pesquisador tentar estimar o efeito causal do tabagismo sobre a saúde a partir de dados observacionais, utilizando, por exemplo, a alíquota de imposto sobre o tabaco como um instrumento para fumar em uma regressão de saúde. Se as alíquotas de imposto sobre o tabaco afetam apenas (positivamente, imagina-se) a saúde porque eles afetam o hábito de fumar (mantendo as outras variáveis do modelo fixas), a correlação entre impostos sobre o tabaco e a saúde é uma evidência de que o tabagismo provoca alterações na saúde. Uma estimativa do efeito do tabagismo sobre a saúde podem ser feita também fazendo uso da correlação entre os impostos e os hábitos de fumar.
```



### Erros de mensuração
O problema de erros de mensuração em estudos práticos é bastante comum. Porém, dependendo da natureza do problema pode trazer consequências nefastas a estimação via MQO.

<br>

```{example alunosufrgs}
 Para explicar o rendimento de um aluno da UFRGS, podemos estar interessados em usar como variáveis explicativas (dentre outras): renda familiar, número de horas dedicadas ao estudo, tempo necessário para o trajeto casa-UFRGS, etc. Todas essas variáveis estão sujeitas a erros de mensuração, pois os alunos podem errar (deliberadamente ou não) ao responder à pesquisa. Se os erros forem puramente aleatórios, isto é, não estiverem correlacionados com outras variáveis relevantes, as hipóteses do modelo acima serão satisfeitas.
```

<br>

```{example metaanalise}
A Meta-análise é uma técnica que visa agregar a informação contida em várias fontes. Em áreas como música, cinema e televisão são muito comuns os sites que apresentam resumos das críticas de um determinado álbum/filme/série em uma única avaliação agregada. Exemplos são os sites Rotten Tomatoes, Metacritic, Allmusic, dentre muitos outros. A idéia estatística destes sites é obter uma avaliação para um determinado assunto a partir da análise agragada de avaliações dadas por críticos, espectadores, mídia, blogs, sites, etc. Cada avaliação obtida é agregada ao total, de onde uma avaliação única é calculada. Para exemplificar vamos supor que estamos interessados na avaliação do último álbum do Metallica (Hard Wired... to Self-Destruct, 2016). Para isso, estabelecemos uma escala a avaliação do álbum e passamos a vasculhar a internet por informações a respeito do álbum. Vamos supor que encontramos 20 sites com avaliações do álbum. Cada uma dessas avaliações é baseada em diversas avaliações individuais de pessoas que visitaram o site. Por exemplo, a avaliação final de um determinado site é dada pela média das avaliações dos visitantes do site. No final, teremos coletado 20 avaliações de sites especializados, onde cada avaliação representa a média dos indivíduos que avaliaram o álbum. Desta forma os dados que coletamos não representam a opinião de ouvintes individuais (a população neste caso), mas a média dessas opiniões, que pode ser diferente de todas as avaliações dadas e que certamente varia de site pra site. Esta avaliação, portanto, considerada como uma observação de indivíduos da população, traz consigo um erro aleatório de medição gerada pelo agregamento das informações individuais.
```


### Variável com erro de medição

Considere o modelo de regressão simples:
\begin{equation}
Y = \beta_0 + \beta_1 X + \varepsilon,
(\#eq:ERROM)
\end{equation}
em que $\mbox{Cov}(X,\varepsilon) = 0$ e $\mbox{Var}(\varepsilon)=\sigma^2_\varepsilon$. A princípio, nesse contexto a estimação por MQO deveria gerar estimadores consistentes dos parâmetros. Vamos supor que, por algum motivo, a variável $X$ seja observada com um erro aleatório. Isto é, suponha que observamos na prática observamos
\begin{equation}
X^* = X + e,
(\#eq:ERROM1)
\end{equation}
onde assumimos que
\[\mathbb{E}(e) = 0; \quad \mbox{Cov}(X,e) = 0; \quad \mbox{Cov}(e,\varepsilon) = 0; \quad \mbox{ e }  \mbox{Var}(e)=\sigma_e^2>0.\]
A aleatoriedade dos erros é fundamental na análise que segue. Reescrevendo o modelo \@ref(eqERROM) em função da variável observada $X^*$:
\begin{align}
Y = \beta_0 + \beta_1 X + \varepsilon = \beta_0 + \beta_1( X^* - e) + \varepsilon=\beta_0 + \beta_1 X^* + \xi,
(\#eq:neghs)
\end{align}
onde $\xi=\varepsilon -\beta_1 e$ faz o papel de erro na regressão. Observe que os estimadores via MQO de $\beta_0$ e $\beta_1$ em \@ref(neghs) são exatamente os mesmos de \@ref(eqERROM), embora seja esta última regressão que estamos efetivamente estimando dada a presença de erros aleatórios nas observações. Agora
\begin{align*}
\mbox{Cov}( X^*, \xi )&=\mbox{Cov}(X + e, \varepsilon -\beta_1 e) =  \mbox{Cov}(X,\varepsilon)-\beta_1\mbox{Cov}(X,e)+\mbox{Cov}(e,\varepsilon)-\beta_1\mbox{Var}(e)\\
&=-\beta_1\sigma_e^2\neq 0.
\end{align*}
Em outras palavras, a estimação via MQO na presença de variáveis com erro (aleatório) de medição resulta em estimativas inconsistentes. Observe ainda que, dada uma amostra de tamanho $n$ do modelo \@ref(eqERROM),

\[ \hat{\beta}=\frac{\sum_{i=1}^{n}(x_i-\overline{x})y_i}{\sum_{i=1}^{n}(x_i-\overline{x})^2}
            =\beta+\frac{\sum_{i=1}^{n}(x_i-\overline{x})\varepsilon_i}{\sum_{i=1}^{n}(x_i-\overline{x})^2},\]
e note que $\mbox{Var}( X^* ) = \mbox{Var}( X ) + \mbox{Var}( e ) = \sigma_{X}^2+\sigma_e^2$, de onde segue que
\[\mathrm{Plim}(\hat\beta_1) = \beta_1 + \frac{\mbox{Cov}(X^*, \varepsilon )}{\mbox{Var}(X^*)}=\beta_1-\frac{ \beta_1 \sigma_e^2}{\sigma_{X}^2 + \sigma_e^2} =\beta_1\left(1-\frac{\sigma_e^2}{\sigma_{X}^2 + \sigma_e^2}\right)\neq 0.\]




## Variável instrumental

Considere  o modelo
\begin{equation}
Y=\beta_0+\beta_1X + \varepsilon,
(\#eq:modvi)
\end{equation}
em que $\mbox{Cov}(X,\varepsilon)\neq 0$. Neste caso, os estimadores de MQO para $\beta_0$ e $\beta_1$ são viciados e inconsistentes e o problema é obter um estimador para estes parâmetros que apresentem propriedades melhores que o estimador de MQO. Para isso estudaremos o método de Variáveis Instrumentais.

Suponha que temos uma variável $Z$ satisfazendo
\begin{align}
\mbox{Cov}(Z,\varepsilon)&=0 (\#eq:condvi1)\\
\mbox{Cov}(Z,X)&\neq 0. (\#eq:condvi2)
\end{align}
Uma variável $Z$ satisfazendo \@ref(eq:condvi1) e \@ref(eq:condvi2) é chamada de \emph{Variável Instrumental}, ou ainda, um \emph{instrumento} para a variável $X$. Por razões que ficarão claras na prática, é desejável que $|\mbox{Cor}(Z,X)|$ seja a mais alta possível.

A condição \@ref(eq:condvi2) é chamada de \emph{relevância do intrumento} enquanto \eqref{eqConBI_1} é chamada de \emph{exogeneidade do instrumento}.

Uma das maiores críticas em relação ao método de variáveis instrumentais é que a condição \@ref(eq:condvi1) não pode ser testada diretamente, pois o erro é não-observável.  Desta forma, para justificarmos a validade da condição \@ref(eq:condvi1) precisamos recorrer à introspecção econômica e/ou argumentos filosóficos.
%É necessário uma boa "historinha" para justificar o instrumento!
A condição \@ref(eq:condvi2), porém, pode ser testada indiretamente via uma regressão de $X$ em $Z$ (teste de significância de qual coeficiente?) ou ainda de um teste de hipótese direto do tipo $H_0:\mbox{Cor}(Z,X)=0 \,  \, vs. \, \, H_1:\mbox{Cor}(Z,X)\neq 0$

Infelizmente, é muito difícil encontrar instrumentos válidos para as variáveis de um determinado problema. Uma das razões dessa dificuldade reside no fato de que as duas condições requeridas de um instrumento são muitas vezes conflitantes, pois temos 3 variáveis $X$, $Z$ e $\varepsilon$ tais que $Z$ é correlacionado com $X$ que por sua vez é correlacionado com $\varepsilon$, mas $Z$ não pode ser correlacionado com $\varepsilon$.

```{example logsal,name="Estimação de equação de salário em função da educação"}
|    Variável omitida: **aptidão** do indivíduo - torna viesado e inconsistente o coeficiente da educação.

|    Possível instrumento: **educação da mãe** (correlacionada com a educação do indivíduo).

|    Mas, educação da mãe também deve ser correlacionada com a habilidade do indivíduo,
presente no erro? Nesse caso, não seria um bom instrumento.

|   **Um possível instrumento seria o número de irmãos** - não correlacionado com $aptid$  - correlacionado com $educ$  (negativamente).

```



### Diferença entre proxy e variável instrumental

A  `r colorize(" variável proxy ", "blue")`    é  caracterizada por:

|    não ser correlacionada com o termo de erro  do modelo;

|    correlacionada com a variável não observada.


A  `r colorize(" variável instrumental ", "blue")`  é caracterizada por

|    i) *Não ser correlacionada com o termo de erro  do modelo,  ou seja, não correlacionada com $aptid$ no exemplo  \@ref(exm:logsal)*;

|    ii) *Correlacionada com a variável endógena, ou seja,  no caso do  exemplo \@ref(exm:logsal), ela deve ser correlacionada com $educ$*.


No  exemplo \@ref(exm:logsal) uma boa proxy seria:

\begin{center}
$QI$=$\begin{cases} &\mbox{correlacionada com $aptid$};\\
    &\mbox{não correlacionada  com o erro},
   \end{cases}$
\end{center}

e um bom instrumento é o *número de irmãos* ($nir$), como visto anteriormente.

\begin{center}
$nir$=$\begin{cases} &\mbox{não correlacionada com $aptid$ e, portanto, não  correlacionada
                                        com o erro};\\
    &\mbox{correlacionada com educação (negativamente)},
   \end{cases}$
 \end{center}



### O método de estimação por variável instrumental

Para descrever o método de estimação por variável instrumental, considere  o seguinte modelo:
\begin{equation}
Y=\beta_0+\beta_1 X  +\varepsilon.
(\#eq:vi1)
\end{equation}
em que $\mbox{Cov}(X,\varepsilon)\neq0$ e seja $Z$ um instrumento para $X$. Para obtermos os *Estimadores de Variável Instrumental* para $\beta_0$ e $\beta_1$, começamos calculando a covariância entre $Z$ e $Y$ como segue:
\begin{align*}
\mbox{Cov}(Z,Y)&=\mbox{Cov}(Z,\beta_0+\beta_1 X  +\varepsilon)=\underbrace{\mbox{Cov}(Z,\beta_0)}_{=0}+\mbox{Cov}(Z,\beta_1 X)  +\underbrace{\mbox{Cov}(Z,\varepsilon)}_{=0}\\
&=\beta_1\mbox{Cov}(Z,X)
\end{align*}
de onde segue que
\begin{align}
\beta_1=\frac{\mbox{Cov}(Z,Y)}{\mbox{Cov}(Z,X)}.
(\#eq:vicima)
\end{align}
Dada uma amostra de tamanho $n$ de $X$, $Y$ e $Z$, obtemos o estimador de VI para $\beta_1$ substituindo-se as covariâncias que aparecem em \@ref(eq:vicima) por suas versões amostrais, isto é,
\[\hat\beta_{1VI}=\frac{\sum_{i=1}^n(z_i-\bar{z})(y_i-\bar{y})}{\sum_{i=1}^n(z_i-\bar{z})(x_i-\bar{x})} =\frac{\sum_{i=1}^nz_iy_i-n\bar{z}\bar{y}}{\sum_{i=1}^nz_ix_i-n\bar{z}\bar{x}}\,.\]

Da mesma maneira como procedemos no caso de MQO, o estimador de VI para $\beta_0$ é dado por
\[ \hat{\beta}_{0VI}=\overline{Y}-\hat{\beta}_{1VI}\overline{X}.\]



## Inferência com o estimador por variável instrumental

Pode-se mostrar que para $n$ grande

\begin{equation}
 \hat{\beta}_{1VI} \,\,\,\, \approx \,\,\,\,\,N\,  \left(\beta_1,\frac{\sigma_\varepsilon^2}{n\sigma_X^2\rho_{XZ}^2}\right),
 (\#eq:bvi)
\end{equation}
ou  seja, para $n$ grande a variância do estimador é dada por


\begin{equation}
\mbox{Var}( \hat{\beta}_{1VI} ) =\frac{\mbox{Var}( \varepsilon )}{n \mbox{Var}(X) \mbox{Cor}(X,Z)^2 }=\frac{\sigma_\varepsilon^2}{n\sigma_X^2\rho_{XZ}^2}.
(\#eq:bla)
\end{equation}
A equação \ref(eq:bla) nos revela algo fundamental na escolha de um bom instrumento: quanto maior a correlação entre o instrumento e a variável, menor é a variância do estimador de VI. Por esta razão, devemos procurar um instrumento que tenha a mais alta correlação possível com $X$. Sabemos que
\begin{equation}
 \mbox{Var}(\hat{\beta}_{1MQO})=\frac{\sigma_\varepsilon^2}{n\sigma_X^2},
 (\#eq:varvi)
\end{equation}
e desta forma obtemos que
\[\mbox{Var}( \hat{\beta}_{1VI} ) =\frac{\sigma_\varepsilon^2}{n\sigma_X^2\rho_{XZ}^2} = \frac{\mbox{Var}(\hat{\beta}_{1MQO})}{\rho_{XZ}^2}\]
de onde concluímos que $\mbox{Var}( \hat{\beta}_{1VI} )\geq \mbox{Var}(\hat{\beta}_{1MQO})$ com igualdade ocorrendo se, e somente se, $|\mbox{Cor}(X,Z)|=1$. Ou seja, a menos que $Z$ seja um instrumento perfeito para $X$ (o que não ocorre na prática), o estimador de MQO sempre possui menor variância que o estimador de VI.

O viés assintótico de VI e MQO pode ser estudado usando os respectivos limites de probabilidade, que são:

\begin{equation}
 \mathrm{plim}(\hat{\beta}_{1VI})=\beta_1+\frac{\mbox{Cor}(z,\varepsilon)}{\mbox{Cor}(X,Z)}\frac{\sigma_\varepsilon}{\sigma_X}
 (\#eq:viesassvi)
\end{equation}
e
\begin{equation}
\mathrm{plim}(\hat{\beta}_{1MQO})=\beta_1+\mbox{Cor}r(X,\varepsilon)\frac{\sigma_\varepsilon}{\sigma_X}.
(\#eq:viesassvi2)
\end{equation}


### Teste de hipóteses 
Consideremos o seguinte problema

\begin{equation}
 \log(sal\acute{a}rio)=\beta_0+\beta_1 educ+u,
 (\#eq:thlogsal)
\end{equation}
em que $\mbox{Cov}(educ,u)\neq 0$. Seja o \emph{número de irmãos}, ($nir$) um instrumento.
Queremos testar a  significância de  $\hat{\beta}_{1VI}$. Os passos para esse teste  são:

|    i) Obter $$\hat{\beta}_{1VI}=\frac{\sum_{i=1}^{n}(nir_i-\overline{nir})(y_i-\overline{y})}
              {\sum_{i=1}^{n}(nir_i-\overline{nir})(x_i-\overline{x})};$$

|    ii) Obter  $$\hat{\sigma}^2=\frac{\sum_{i=1}^{n}{\hat{u}^{2}_{i_{VI}}}}{n-2}, $$
      em  que  $\hat{u}_i^{VI}=y_i-\hat{\beta}_{0VI}-\hat{\beta}_{1VI}educ$;

|    iii) Obter $R^2_{educ,nir}$, que é o $R^2$ de $$educ=\alpha_0+\alpha_1nir+v;$$

|    vi) Obter a estimativa do desvio padrão
$$S(\hat{\beta}_{1VI})=\sqrt{\frac{\hat{\sigma}^2}{\sum_{i=1}^{n}(x_i-\overline{x})^2R^2_{educ,nir}}};$$

|    v) Teste:$\begin{cases}
             H_0:  &  \beta_{1VI}=0; \\
             H_1:  &  \beta_{1VI}\neq 0.
            \end{cases}$




Um exemplo para ver a diferença entre as estimativas obtidas pelos dois métodos de estimação (MQO e VI), é o exemplo abaixo, reproduzido com pequenas adaptações do exemplo 15.1 do @wooldridge2016.

```{example mroz}
Utilizamos os dados sobre mulheres casadas que trabalham contidos no arquivo MROZ.RAW para estimar o retorno da educação no modelo de regressão simples
\[Y=\beta_0+\beta_1 X+\varepsilon,\]
onde $Y$ é o logaritmo do salário das mulheres casadas por hora e $X$ representa a educação. Para comparação, obtemos a reta estimada via MQO para $Y$,
\begin{align}
\hat Y=&-0.185+0.109X\\
&(0.185) \ \ (0.014)\nonumber
(\#eq:abs)
\end{align}
onde $n=428$. Obtemos ainda $R^2=0.118$. A estimativa de $\beta_1$ implica um retorno de perto de 11\% para um ano a mais de educação. Em seguida utilizaremos a variável $Z = $ educação dos pais como variável instrumental para $X$. Primeiramente, para determinarmos que $\mbox{Cov}(Z,X)\neq0$, fazemos uma regressão simples de $X$ em $Z$ de onde obtemos a reta de ajustada
\begin{align*}
\hat X=&10.24+0.269Z\\
&(0.28) \ \ (0.029)
\end{align*}
com $R^2=0.173$. A utilização de $Z$ como uma VI para $X$ produz
\begin{align}
\hat Y=&-0.441+0.059X\\
&(0.446) \ \ (0.035)\nonumber
(\#eq:abs)
\end{align}
com $R^2=0.093$. A estimativa de VI do retorno da educação é de 5.9%, que é pouco mais da metade da estimativa de MQO. Isso \emph{sugere} que a estimativa de MQO é alta demais. Porém devemos lembrar que como as estimativas são baseadas em dados amostrais, não temos como saber qual está mais próximo do verdadeiro valor. Note ainda que o erro padrão da estimativa de VI para $\beta_1$ é duas vezes maior que a de MQO. O intervalo de confiança à 95% de $\beta_1$ utilizando MQO é muito mais estreito do que utilizando VI; de fato, o intervalo de confiança da VI contém a estimativa de MQO. Portanto, embora as diferenças entre \@ref(eq:abs) e \@ref(eq:abs2) sejam grandes na prática, não podemos afirmar com certeza que as diferenças são estatísticamente significantes. O fato de o intervalo de VI conter a estimativa de MQO é uma evidência contra essa hipótese.
```



## Variáveis instrumentais em modelos de regressão múltipla

O estimador de VI para o modelo  de regressão simples é facilmente estendido para o caso de regressão múltipla. Consideremos inicialmente o caso em  que somente um dos regressores é endógeno. A equação estrutural do  modelo linear padrão com duas variáveis explicativas é
\begin{equation}
 Y_1=\beta_0+\beta_1 Y_2+\beta_2Z+\varepsilon.
 (\#eq:VIreegMult)
\end{equation}
Usamos essa notação para identificar as  variáveis endógenas ($Y$'s) e as variáveis exógenas
($Z$'s).
Um exemplo para \@ref(eq:VIreegMult) é

\begin{equation}
 \log(\mathrm{salario})=\beta_0+\beta_1\mathrm{educ}+\beta_2\mathrm{exper}+\varepsilon,
 (\#eq:VIreegMult2)
\end{equation}
em que $Y_1=$ logaritmo do salário, $Y_2=$ educ e $Z_1=$ exper. Assim, estamos supondo que
exper  é exógeno e,  por razões habituais, presumimos que educ seja  correlacionado com $\varepsilon$.

Se  estimarmos \@ref(eq:VIreegMult) por MQO, todos os estimadores serão viesados  e inconsistentes. Assim, seguimos a estratégia da  seção anterior  para encontrar  uma VI para $Y_2$. Como $Z_1$ aparece como variável explicativa, devemos procurar outra variável exógena (vamos chamá-la de $Z_2$) que seja correlacionada com $Y_2$.

A correlação de $Z_2$ e $Y_2$ pode ser afetada por $Z_1$ que aparece na regressão \@ref(eq:VIreegMult). Devemos  nos certificar que na presença de $Z_1$, $Y_2$  e $Z_2$  ainda são correlacionados.
Essa  condição pode ser verificada a partir da regressão

\begin{equation}
 Y_2=\pi_0+\pi_1Z_1+\pi_2Z_2+\epsilon,
 (\#eq:fromared)
\end{equation}
em que $\mathbb{E}(\epsilon)=0$, $\mbox{Cov}(Z_1,\epsilon)=0$, $\mbox{Cov}(Z_2,\epsilon)=0$ e  os $\pi_j$ são parâmetros  desconhecidos. A condição de identificação fundamental é que
\[\pi_2\neq 0,\] a qual pode ser testada usando-se um teste $t$.


<br>

```{remark rmvi1}
 A  equação \@ref(eq:formared) é um exemplo de uma \emph{equação na forma reduzida},
significando que escrevemos uma variável endógena em função de exógenas. O nome ajuda a distingui-lá da equação estrutural \@ref(eq:VIreegMult).
```

A adição de mais variáveis explicativas exógenas ao modelo é  direta. O modelo estrutural com $k-1$ variáveis exógenas ($Z_1,Z_2,\ldots,Z_{k-1}$) e uma variável endógena ($Y_2$) é


\begin{equation}
 Y_1=\beta_0+\beta_1Y_2+\beta_2Z_1+\beta_3Z_2+\ldots+\beta_kZ_{k-1}+\varepsilon.
  (\#eq:fromaestvv)
\end{equation}
Se $Z_k$ é  uma variável exógena e queremos usá-la como uma VI para $Y_2$, devemos
proceder de forma semelhante a \@ref(eq:formared), escrevendo a equação na forma reduzida


\begin{equation}
 Y_2=\pi_0+\pi_1Z_1+\pi_2Z_2+\cdots+\pi_{k-1}Z_{k-1}+\pi_kZ_k+v_2,
 (\#eq:fromaredvv)
\end{equation}
para a qual é necessário que exista alguma correlação parcial entre $Z_k$ e $Y_2$:
\[\pi_k\neq 0.\]


### Mínimos quadrados em dois estágios (MQ2E)

Nesta  subseção vamos mostrar a equivalência do estimador VI com MQ2E. Para isso
consideremos  a equação estrutural com uma variável endógena


\begin{equation}
Y=\beta_0+\beta_1 X  +\varepsilon,
(\#eq:mq2e1)
\end{equation}
em que $\mbox{Cov}(X,\varepsilon)\neq 0$. Seja $Z$ um instrumento para $X$.

<br>

O procedimento MQ2E consiste em:

|    i) Estimar a equação reduzida
   \begin{equation}
    X=\alpha_0+\alpha_1 Z  +\epsilon,
    (\#eq:mq2e2)
   \end{equation}
encontrando as estimativas  de $\alpha_0$ e $\alpha_1$ via MQO.

|    ii) Obter a reta ajustada
\[    \hat{x_i}=\hat{\alpha}_0+\hat{\alpha}_1 z_i.\]

|    iii) Estimar $\beta_0$ e  $\beta_1$ via MQO no seguinte modelo:

\begin{equation}
 y_i=\beta_0+\beta_1 \hat{x}_i  +\eta_i,
 (\#eq:yhatx)
\end{equation}
para $i=1,\ldots,n$,  ou seja, usar $\hat{X}$ como uma VI para $X$.


Esse procedimento resulta em uma estimativa para $\beta_1$ equivalente a $\hat{\beta}_{1VI}$, como será demonstrado a seguir.

  Note que:

\begin{eqnarray*}
   \hat{x}_i&=& \hat{\alpha}_0+\hat{\alpha}_1 z_i\\
            &=&\overline{x}-\hat{\alpha}_1\overline{z}+\hat{\alpha}_1z_i\\
	    &=&\overline{x}+\hat{\alpha}_1(z_i-\overline{z}).
\end{eqnarray*}
De \@ref(eq:yhatx), segue que
\begin{equation*}
 \hat{\beta_1}=\frac{\sum_{i=1}^{n}(\hat{x}_i-\overline{\hat{x}})(y_i-\overline{y})}
               {\sum_{i=1}^{n}(\hat{x}_i-\overline{\hat{x}})^2}.
\end{equation*}
Pode-se mostrar facilmente que $\overline{\hat{x}}=\overline{x}$.  Logo,
\begin{eqnarray*}
 \hat{\beta_1}&=&\frac{\sum_{i=1}^{n}\hat{\alpha}_1(z_i-\overline{z})(y_i-\overline{y})}
               {\sum_{i=1}^{n}(\hat{\alpha}_1(z_i-\overline{z}))^2}\\
	      &=&\hat{\alpha}_1\frac{\sum_{i=1}^{n}(z_i-\overline{z})(y_i-\overline{y})}
	       {\hat{\alpha}_1^2\sum_{i=1}^{n}(z_i-\overline{z})^2}\\
	      &=&\frac{\sum_{i=1}^{n}(z_i-\overline{z})(y_i-\overline{y})}
	         { \frac{\sum_{i=1}^{n}(z_i-\overline{z})(x_i-\overline{x})}{\sum_{i=1}^{n}(z_i-\overline{z})^2}\sum_{i=1}^{n}(z_i-\overline{z})^2}\\
	      &=&\frac{\sum_{i=1}^{n}(z_i-\overline{z})(y_i-\overline{y})}
		{\sum_{i=1}^{n}(z_i-\overline{z})(x_i-\overline{x})}\\
	      &=&\hat{\beta}_{1VI}.
\end{eqnarray*}

Quando existir mais de uma VI disponível, digamos $Z_1,Z_2$  $Z_3$, qualquer combinação linear destas VI's também será uma VI válida. Devemos escolher a combinação linear com a mais alta correlação com a variável endógena $Y_2$. Isto acaba sendo fornecido pela equação na forma reduzida de $Y_2$, que é dada por

\begin{equation}
 Y_2=\pi_0+\pi_1Z_1+\pi_2Z_2+\pi_3Z_3+\epsilon,
 (\#eq:formaredvv123)
\end{equation}
em que $\mathbb{E}(\epsilon)=0,$ $\mbox{Cov}(Z_1,\epsilon)=0$, $\mbox{Cov}(Z_2,\epsilon)=0$ e $\mbox{Cov}(Z_3,\epsilon)=0$. Portanto, a melhor VI de $Y_2$  é a combinação  linear dos $Z_j$, que denotaremos por
  \begin{equation}
   Y_2^*=\pi_0+\pi_1Z_1+\pi_2Z_2+\pi_3Z_3.
    (\#eq:cly)
  \end{equation}

Para que esta VI não seja perfeitamente correlacionada com $Z_1$, precisamos que
\begin{equation}
\pi_2\neq 0\,\,\,\mbox{ ou }\,\,\,\pi_3\neq 0.
 (\#eq:pi1oupi2)
\end{equation}
Se  essa hipótese de identificação, a qual pode ser testada usando-se um teste $F$, for satisfeita, então podemos usar $Y_2^*$ como VI para $Y_2$.

<br>

```{remark rmvi2}
Quando o problema é a existência de variáveis explicativas endógenas múltiplas, será necessária que existam pelo menos tantas variáveis exógenas excluídas do modelo quantas forem as endógenas incluídas.
```

<br>

```{remark rmvi3}
Se para cada endógena existe uma única exógena, então podemos chamar o método de estimação de VI ou MQ2E.
```

<br>

```{remark rmvi4}
Os testes de hipóteses múltiplas em um modelo estimado por MQ2E devem ser feitos com bastante cuidado. É possível que na estimação por VI ou MQ2E o $R^2$ seja negativo. Isso influencia diretamente a estatística $F$ e consequentemente qualquer conclusão a respeito das hipóteses.
```



## Testes de endogeneidade

Como visto  anteriormente, a condição \@ref(eq:condvi1) não  pode ser testada, logo não podemos ter certeza se os regressores (variáveis explicativas) estão ou não correlacionados com o erro. Se não houver correlação, é melhor utilizar mínimos quadrados ordinários que o estimador de variáveis instrumentais  ou MQ2E. No entanto, pela estimação pura e simples é impossível descobrir se há correlação entre os regressores e o erro.

		
### Teste de Hausmann

O teste de especificação proposto  por @hausman1978 é um teste utilizado  para
avaliar a consistência de um estimador comparado a um outro estimador alternativo  e  pode ser utilizado  no contexto de endogeneidade.

A lógica de Hausmann é a seguinte: sob a hipótese nula (ausência de correlação entre os
regressores e o termo de erro), o econometrista tem em mãos dois estimadores consistentes
 para a matriz de parâmetros: o estimador de mínimos quadrados ordinários $\hat{\beta}_{MQO}$ e o estimador de variáveis instrumentais  $\hat{\beta}_{VI}$. Sob a hipótese alternativa, no entanto, somente um destes, $\hat{\beta}_{VI}$, é consistente. Portanto, a sugestão foi examinar a diferença
$d= \hat{\beta}_{VI}-\hat{\beta}_{MQO}$. O resultado desta diferença converge em probabilidade para zero apenas sob a hipótese nula. Podemos testar esta hipótese usando o teste de Wald.


### Teste de regressão
Para ilustrar, suponha que temos uma única variável suspeita de ser endógena,

\begin{equation}
 Y_1=\beta_0+\beta_1Y_2+\beta_2Z_1+\beta_3Z_2+\varepsilon,
  (\#eq:regtest)
 \end{equation}
em que $Z_1$ e $Z_2$ são exógenos. Temos duas outras variáveis exógenas, $Z_3$ e $Z_4$,
que não aparecem no modelo \@ref(eq:regtest). Se $y2$ for não correlacionado com $\varepsilon$,
devemos estimar \@ref(eq:regtest) por  MQO. @wooldridge2016 sugere que é mais fácil
usar um  teste de regressão para testar se $Y_2$ é endógena. Isto é feito com base na
estimação da forma reduzida de $Y_2$, que neste caso é

\begin{equation}
 Y_2=\pi_0+\pi_1Z_1+\pi_2Z_2+\pi_3Z_3+\pi_4Z_4+\epsilon.
 (\#eq:regtest2)
\end{equation}

Agora,  como cada $Z_j$ é não correlacionado com $\varepsilon$,  $Y_2$  será não  correlacionado
com $\varepsilon$  se,  e  somente  se, $\epsilon$  for correlacionado com $\varepsilon$; isso é o que queremos testar. Deveríamos escrever o modelo
\begin{equation}
 \varepsilon=\delta_1\epsilon+\eta_1
  (\#eq:regtest3)
\end{equation}
e testar se $\delta_1=0$. No entanto,  não temos $\varepsilon$ nem $\epsilon$. A sugestão é usar $\hat{\epsilon}_2$ como um regressor  em  \@ref(eq:regtest).

O método pode ser resumido da seguinte forma:

|    i) Obter via  MQO os  resíduos
       $$\hat\epsilon=Y_2-\hat{\pi}_0+\hat{\pi}_1Z_1+\hat{\pi}_2Z_2+\hat{\pi}_3Z_3+\hat{\pi}_4Z_4;$$

|    ii)Estimar via  MQO a regressão
       \begin{equation*}
        Y_1=\beta_0+\beta_1Y_2+\beta_2Z_1+\beta_3Z_2+\delta_1\hat{Y}_2+e;
       \end{equation*}

|    iii)  Testar $H_0:\delta_1=0$ via teste $t$ (robusto a heterocedasticidade). Se rejeitamos $H_0$ a  um pequeno nível de significância, concluímos que $Y_2$ é endógeno porque $\epsilon$ e $\varepsilon$ são  correlacionados.





\newpage
## Exercícios



```{exercise exvi1}
Qual a motivação para o uso da estimação por variáveis instrumentais? Como se pode definir um bom instrumento?
```

<br>

```{exercise exvi2}
O que são variáveis endógenas e exógenas?
```

<br>

```{exercise exvi3}
Quais são as características de uma boa variável proxy e um bom instrumento?
```

<br>

```{exercise exvi4}
Seja $X$ a matriz cujas colunas são compostas pelas variáveis $x_1,\ldots,x_k$. As condições $\mathbb{E}[u/X]=0$ e $\mbox{Cov}(u,x_j)=0$, para todo $j=1,\ldots,k$, são equivalentes? Explique o que estas condições significam na prática.
```

<br>

```{exercise exvi5}
Dê um exemplo em que a condição $\mathbb{E}[u/X]$ não é válida.
```


<br>

```{exercise exvi6}
Quais as propriedades do estimador de variáveis instrumentais quando se possui uma variável instrumental fraca (fraco instrumento)?
```

<br>

```{exercise exvi7}
Qual a diferença da estimação de variáveis instrumentais para a estimação de mínimos quadrados em dois estágios? Explique e mostre as hipóteses de identificação necessárias. ```

<br>

```{exercise exvi8}
Em um modelo com duas variáveis regressoras,
$$y=\beta_0+\beta_1x_1+\beta_2x_2+u,$$
em que $\mbox{Cov}(x_1,x_2)\neq 0$, as estimativas dos parâmetros $\beta_1$  e $\beta_2$ obtidas via MQO serão viesadas?
```

<br>

```{exercise exvi9}
Suponha que você queira estimar o efeito da frequência às aulas sobre o desempenho dos alunos (\emph{respad} - resultado padronizado em um exame final).
Um modelo básico é
\[respad=\beta_0+\beta_1taxafreq+\beta_2prsGPA+\beta_3ACT+u,\] em que
\emph{taxafreq} é a taxa de frequência, $prsGPA$ é a média geral das notas em curso superior no último semestre.

|    a) Defina $dist$ como a distância da residência do aluno até o local de estudos. Você considera que $dist$ é não correlacionada com $u$?
  
|    b)  Suponha que $dist$ e $u$ não sejam correlacionadas, que outra hipótese $dist$ terá que satisfazer para ser uma VI válida de $taxafreq$?
  
|    c)  Suponha que adicionemos o termo de interação $prsGPA.taxafreq$
 \[respad=\beta_0+\beta_1taxafreq+\beta_2prsGPA+\beta_3ACT+\beta_4 prsGPA.taxafreq+u.\]
 Se $taxafreq$ for correlacionada com $u$, então em geral, $prsGPA.taxafreq$ também será. O que poderia ser uma boa VI para $prsGPA.taxafreq$?

```

<br>

```{exercise exvi10}
Em um modelo com duas variáveis regressoras,
$$y=\beta_0+\beta_1x_1+\beta_2x_2+u,$$
em que $x_2$ é endógena, a estimativa do parâmetro $\beta_1$ obtida via MQO é viesada mesmo que $\mbox{Cov}(x_1,x_2)=0$?
```

<br>

```{exercise exvi11}
No modelo
$$y=\beta_0+\beta_1x_1+\beta_2x_2+u,$$
a omissão de uma variável explicativa relevante $x_2$, para explicar a variável dependente $y$ torna a estimativa dos coeficientes $\beta_0$ e  $\beta_1$ obtidas via MQO  viesadas?
```

<br>

```{exercise exvi12,name="Experimento de Monte Carlo"}
Esse execício encontra-se no capítulo 8 de @dougherty2011 e relata um experimento de Monte Carlo que investiga o desempenho dos métodos MQO e IV ao estimar a equação de inflação dos preços no modelo de inflação de preços/inflação do salário. Valores numéricos foram atribuídos aos parâmetros das equações da seguinte forma:
\begin{equation}
p = 1.5  + 0.5w +u_p
(\#eq:p)
\end{equation}
$$w = 2.5 + 0.5p - 0.4U + u_w, $$
em que para $U$ foi atribuído os valores $2, 2.25,2.50,\cdots$ aumentando em passos de 0.25 até 6.75. $u_w$ foi gerado como uma
variável aleatória  normal com média 0 e variância unitária, escalado por um fator $0.8$. O termo distúrbio $u_w$ foi gerado de forma independente, como uma variável aleatória  normal com média 0 e variância unitária. Cada repetição do experimento utilizou uma amostra de 20 observações. A tabela a seguir mostra as estimativas via MQO e VI do intercepto, $b_1$, e do coeficiente de $w$, $b_2$, da equação \@ref(eq:p), e os respectivos erros padrões (e.p.).


|       |     |MQO  |     |   |       |VI   |      |
|-------|-----|-----|-----|----|------|-----|------|
|Sample |$b_1$| e.p.($b_1$)| $b_2$ |e.p.($b_2$)| $b_1$ |e.p.($b_1$) |$b_2$ |e.p.($b_2$) |
|1 |0.36 |0.39 |1.11 |0.22 |2.33| 0.97 |0.16 |0.45  |
|2 |0.45 |0.38 |1.06 |0.17 |1.53| 0.57 |0.53 |0.26  |
|3 |0.65 |0.27 |0.94 |0.12 |1.13| 0.32 |0.70 |0.15  |
|4 |0.41 |0.39 |0.98 |0.19 |1.55| 0.59 |0.37 |0.30  |
|5 |0.92 |0.46 |0.77 |0.22 |2.31| 0.71 |0.06 |0.35  |
|6 |0.26 |0.35 |1.09 |0.16 |1.24| 0.52 |0.59 |0.25  |
|7 |0.31 |0.39 |1.00 |0.19 |1.52| 0.62 |0.33 |0.32  |
|8 |1.06 |0.38 |0.82 |0.16 |1.95| 0.51 |0.41 |0.22  |
|9 |-0.08| 0.36| 1.16|0.18 |1.11| 0.62 |0.45 |0.33  |
|10| 1.12| 0.43| 0.69|0.20 |2.26| 0.61 |0.13 |0.29  |


Compare as estimativas via MQO e VI em termos de vício e variância.
```

<br>

```{exercise exvi13,name="ANPEC 2008"}
Suponha que o modelo abaixo descreva as relações entre quatro variáveis aleatórias escalares: $y$,$X$,$Z$, e $V$.
$$\mathbb{E}(y/X,Z)=\beta_0+\beta_1X+\beta_2Z$$
$$X=\alpha_0+\alpha_1Z+v,\,\,\,\,\mathbb{E}(v/Z,X)=E(v/Z)=\mathbb{E}(v/X)=\mathbb{E}(v)=0.$$
Suponha, ainda, que $\beta_0\neq 0$, $\beta_1\neq 0$, $\beta_2\neq 0$, $\alpha_0\neq 0$ e $\alpha_1\neq 0$.

|    a) Calcule $\mathbb{E}(y/Z).$
  
|    b) Seja $y=\beta_0+\beta_1X+\beta_2Z+u$. Calcule $\mathbb{E}(u/X,Z)$.

|    c) Calcule $\mathbb{E}(X/Z)$.

|    d) Seja $$y=\theta_0+\theta_1Z+\varepsilon$$ em que $\theta_0=\beta_0+\beta_1\alpha_0$ e $\theta_1=\beta_1\alpha_1+\beta_2$. Calcule $\mathbb{E}(\varepsilon/Z)$.

|    e) Considere uma amostra de tamanho $n$ das variáveis $y$, $X$ e $Z$. O estimador $$T=\frac{\sum_{i=1}{n}y_i(z_i-\overline{z})}{\sum_{i=1}{n}(z_i-\overline{z})^2}$$ é um estimador não tendencioso para $\theta_1=\beta_1\alpha_1+\beta_2$?

```

<br>

```{exercise exvi14}
Mostre que o $R^2$ da estimativa via VI pode ser negativo.
```

<br>

```{exercise exvi15}
Suponha que o modelo \[ y=\beta_0+\beta_1x+u,\] em que $x$ é endógena e $z$ é um instrumento para $x$.
Para comparar a variância de VI com MQO suponha que $\sigma_x=\sigma_u$, ou seja, a variação populacional
contida no termo de erro seja a mesma contida em $x$. Suponha que a variável instrumental $z$ seja levemente correlacionada
com $u$, $\mbox{Cor}(z,u)=0,1.$ Suponha também que $z$ e $x$ tenha uma correlação um pouco maior: $\mbox{Cor}(z,x)=0,2.$

|    a) Qual será o viés assintótico no estimador de VI?
  
|    b) Quanta correlação deverá existir entre $x$ e $u$ antes que o MQO tenha mais viés assintótico que o MQ2E?

```









